### ISSUE TITLE
[Bug, 7.0.0 regression] There is no Splatfest music when I load the game

### ISSUE THREAD

**Issue by ideapc** [Coxxs/public-pchtxt#11]
For some reason there is no Splatfest music when I load the game. Was fine on 6.1.0, happens since 7.0.0. Reentering the city helps, but previously there was music just when I pass the title screen.

**Comment by ideapc** [comment]
There is also no music AT ALL in Inkopolis Square. Reentering the city doesn't help.
https://github.com/Coxxs/public-pchtxt/assets/77688386/e12c41b5-11d6-46ef-a821-250ef1964d4a

**Comment by Coxxs** [comment]
> There is also no music AT ALL in Inkopolis Square on the Splatfest. Reentering the city doesn't help, compared to Inkopolis Plaza. So there's no music, just the crowd noise.

https://twitter.com/OatmealDome/status/1765443753500643377

**Comment by ideapc** [comment]
> > There is also no music AT ALL in Inkopolis Square on the Splatfest. Reentering the city doesn't help, compared to Inkopolis Plaza. So there's no music, just the crowd noise.
> 
> https://twitter.com/OatmealDome/status/1765443753500643377

Ah, ty. Then I will wait for the game update.
