### ISSUE TITLE
[Request/Idea] Show all Versus/Salmon Maps in Map Selection

### ISSUE THREAD

**Issue by skippychubby12** [Coxxs/public-pchtxt#12]
If you created a save file in an emummc and try select any Versus/Salmon map in the shoal or recon that wasn't in the game in launch, they wont be there, i hope its possible to fix this with a code patch

**Comment by ideapc** [comment]
I really hope it can be done! The 12 versus maps are not enough, and same about 3 salmon run maps... the basic game has much more than that, why don't make them usable within the Shoal =(

**Comment by Coxxs** [comment]
Thanks for the suggestion! We will consider releasing this patch after Season 8 starts for content preservation purposes. Until then, you can use save files or modify the RSDB files to unlock map content.

Please note that in the past (specifically, before the start of Season 3), there have been cases of players being console banned simply for joining a room with a new map before the season started (even if they did not mod their console, even if they are using lanplay).

**Comment by ideapc** [comment]
How do I unlock the map content then..? I'm playing on a emulator

**Comment by Coxxs** [comment]
Import a savefile with maps unlocked

or 

Mod and change the season to 0 in `RSDB/CoopSceneInfo.Product.700.rstbl.byml` and `RSDB/VersusSceneInfo.Product.700.rstbl.byml` with [Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox)

**Comment by ideapc** [comment]
> Import a savefile with maps unlocked
> 
> or
> 
> Change the season to 0 in `RSDB/CoopSceneInfo.Product.700.rstbl.byml` and `RSDB/VersusSceneInfo.Product.700.rstbl.byml` with [Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox)

Thank you so much! The season 0 method worked, but I guess it requires all the players to do so, haven't tested it with any people yet.
Hope you'll make a patch that just unlocks stages though. Season 8 is going to be in summer... do we really need to wait this long?

**Comment by Coxxs** [comment]
The patch will have the same effect as a RSDB edit, I believe other players won't need any mod.

**Comment by ideapc** [comment]
> The patch will have the same effect as a RSDB edit, I believe other players won't need any mod.

So yeah, you're right! I tested the season 0 method and it works flawlessly with other players, they don't need the rsdb edit. Thank you! But yeah, waiting for a pchtxt patch as that would be better

**Comment by Coxxs** [comment]
`Show Big Run Stages` patch was added

**Comment by Coxxs** [comment]
`Save Edit* - Season=9 (Unlock Stages and more)` patch was added.
