### ISSUE TITLE
[Request/Idea] Change Splatfest Files (ink colors, icons, etc.) while using offline splatfest patches

### ISSUE THREAD

**Issue by GabIsAwesome** [Coxxs/public-pchtxt#13]
Not sure if this is even possible, but it would be cool to try to change the splatfest files for them to have an actual theme, icons, ink colors and other stuff instead of being all placeholders.

**Comment by ideapc** [comment]
Yes please, maybe even with custom content?

**Comment by Coxxs** [comment]
Thanks for the suggestion! I did try to achieve this using patch but it was too difficult for me. The game expects to obtain fest data files from bcat and npln and decrypt them. Changing to reading them locally and skip decryption requires a lot of mods to the program.
