### ISSUE TITLE
[Request/Idea] Offline Locker room

### ISSUE THREAD

**Issue by ideapc** [Coxxs/public-pchtxt#14]
Hello. I have a suggestion. Can you try making an offline locker room? I know it'd not be really useful, but still, I can buy many things for the locker room using your offline patches, and I'd really like to use them. Setting up a locker room even on offline mode would be very calming.

**Comment by Coxxs** [comment]
I have tried this before, but unfortunately I cannot get it to work :(

**Comment by ideapc** [comment]
Okay
