### ISSUE TITLE
[Request/Idea] Weapons for cash

### ISSUE THREAD

**Issue by ideapc** [Coxxs/public-pchtxt#16]
Suggesting this as Sheldon Licenses are impossible to get offline... until you find a way of making The Shoal giving players exp and stuff. Cash is possible to get without hacking, with the battle bonuses (the dlc) and singleplayer especially side order

**Comment by Coxxs** [comment]
Thanks for the suggestion! I might think of another way to get weapons, but I'm not interested in implementing buying them with money

**Comment by ideapc** [comment]
Oh. I heard there are cash prices for the weapons in the game files so that's why I asked.
