### ISSUE TITLE
[Request/Idea] Implementing Xtrawave into The Shoal (without using scenarios)

### ISSUE THREAD

**Issue by Khalilrk** [Coxxs/public-pchtxt#20]
I have two ideas of how this could be implemented, first one is to port the "smell" meter functionality to the Shoal, which, I admit, is a difficult task, but in theory should be possible. The second idea is to add a slider that toggles the Xtrawave being in the match or not, which is more difficult because you'd need to write separate functionality for it. Also, I am suggesting this because Big Run scenarios can't be saved through the Grizzco Terminal, and therefore you can't play Xtrawave on them in The Shoal.

**Comment by Coxxs** [comment]
`Salmon Run - Force Boss on Wave X [Haxxie]` patches are added. However the king type can only be specified using a scenario for now.

**Comment by Coxxs** [comment]
https://github.com/Coxxs/public-pchtxt/commit/083c71a53c632425502698d0f1533f4a44416d3c
