### ISSUE TITLE
[Request] Grand Splatlands Bowl on The Shoal

### ISSUE THREAD

**Issue by 0-Kas-0** [Coxxs/public-pchtxt#30]
Is it possible to add the Grand Splatlands Bowl as a selectable stage in Turf War (Tricolor) at The Shoal? Thanks!

**Comment by Coxxs** [comment]
https://github.com/Coxxs/public-pchtxt/commit/d7282669fa9ac77c3fb3df575d56195b9a6478bb

**Comment by 0-Kas-0** [comment]
> [d728266](https://github.com/Coxxs/public-pchtxt/commit/d7282669fa9ac77c3fb3df575d56195b9a6478bb)

Thank you! Now it appears in the stage selection. However, when I start a match, the game crashes. Maybe it doesn't really work? I had edited RSDB before to make the map appear, and the same error occurred.

**Comment by Coxxs** [comment]
Thanks!
Fixed in https://github.com/Coxxs/public-pchtxt/commit/1398e292d11910caea674c6a03247d134cbf0368, note that other players may also need the patch to fix the crash.

**Comment by 0-Kas-0** [comment]
It works perfectly now, thank you very much!

**Comment by Coxxs** [comment]
Updated the code, other players *may* not need the patch now (not tested)

**Comment by 0-Kas-0** [comment]
Regarding the use of offline + isolated emuMMC, does this apply to any of the patches? I've seen people use them via lan in the official firmware. I guess it's a matter of taking the risk or not, right?

**Comment by Coxxs** [comment]
If you use patch, you must use an isolated emuMMC, otherwise you run a high risk of getting your device banned by anti cheat. If you join a modded room with an unmodded switch, there are still some risks. (There are cases of people getting banned for *joining* a modded room before Season 3)

**Comment by 0-Kas-0** [comment]
I tested it with some friends who don't have the patch, and it worked fine now
