### ISSUE TITLE
Grand Festival Bowl Tricolor match music does not work properly.

### ISSUE THREAD

**Issue by mganci** [Coxxs/public-pchtxt#31]
When i enter a tricolor match using that map, i can't listen to the right music and sometimes i can't ear it at all.
For the rest the patch work great, maybe this should be a fix or an implementation. Thx in advance!

**Comment by Coxxs** [comment]
This might involve [xlink](https://github.com/shadowninja108/WoomLink)
Not sure how to fix it...
```
     MainVss_00 {
          if (BgmId == 13) {
               run {
                    AssetName = "MainVss_00",
                    RuntimeAssetName = "BGM_Versus_Fes_SAND_3Idol_Trc",
                    GroupName = "Bgm_Default",
                    StopFrame = 30,
                    Priority = 1,
                    BitFlag = 0b00000110 ReferenceType:	(Bitfield),
               }
          }
     }
```

**Comment by Coxxs** [comment]
Found a way, will fix later

**Comment by Coxxs** [comment]
https://github.com/Coxxs/public-pchtxt/commit/6da68484a47da89a9048a8dabd3df4be79cb4adf
