### ISSUE TITLE
Big run stages not showing

### ISSUE THREAD

**Issue by Luigi-is-coo** [Coxxs/public-pchtxt#32]
Okay to cut to the chase
Even though I have the show Big run stages patch enabled 
They don't show up in the shoal
Is that how it is or is there another way to access big run stages
Also I've heard that you can do stuff with scenario codes so how do you do that?

**Comment by Coxxs** [comment]
The "Show Big Run Stages" patch must be applied before the game starts. If you apply it after the game has started, it won't work.

**Comment by Luigi-is-coo** [comment]
What do you mean by before the game starts because I just ran the patch and open to the game and it's still only the first three stages
